FROM composer:2.8.10@sha256:20462d70afcfa999ad75dbd9333194067f4d869078bdb37430339e8d97e541d6
RUN apk add --no-cache php84-pdo_mysql php84-xml php84-mbstring php84-curl
WORKDIR /artifact/papa-website-v2
CMD ["composer", "install", "--no-interaction", "--prefer-dist"]
